-- Create user table
CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    profile_image TEXT
);

-- Create category table
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

-- Create category task
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    creation_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Sin Empezar', 'Empezada', 'Finalizada')),
    id_category BIGINT NOT NULL,
    id_user BIGINT NOT NULL,
    CONSTRAINT task_id_category_fkey FOREIGN KEY (id_category) REFERENCES category(id) ON DELETE CASCADE,
    CONSTRAINT task_id_user_fkey FOREIGN KEY (id_user) REFERENCES user(id) ON DELETE CASCADE
);