-- Create users table to store application users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    profile_image TEXT NOT NULL
);

-- Create categories table for task grouping
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    id_user BIGINT NOT NULL
    -- Foreign key to user with cascade delete
    CONSTRAINT category_id_user_fkey FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE
);

-- Create tasks table with status and foreign keys to categories and users
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    creation_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Sin Empezar', 'Empezada', 'Finalizada')),
    id_category BIGINT NOT NULL,
    id_user BIGINT NOT NULL,
    -- Foreign key to categories with cascade delete
    CONSTRAINT task_id_category_fkey FOREIGN KEY (id_category) REFERENCES categories(id) ON DELETE CASCADE,
    -- Foreign key to users with cascade delete
    CONSTRAINT task_id_user_fkey FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE
);